title: Creating Directories on a Raspberry Pi
hero_image: images/banner.png
description: Learn how to create a directory in two different ways
original_url:
theme: cc-prototype
published: false
ingredient: true
steps:
  - title: Creating Directories on a Raspberry Pi
