---
title: Δημιουργία καταλόγων σε ένα Raspberry Pi
hero_image: images/banner.png
description: Μάθε πώς μπορείς να δημιουργήσεις έναν κατάλογο με δύο διαφορετικούς τρόπους
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "raspbian"
steps:
  - 
    title: Δημιουργία καταλόγων σε ένα Raspberry Pi
